name: Plugins
version: '${project.version}'
main: me.eric.plugins.Plugins
api-version: 1.19
commands:
  announce:
    description: announce
  heal:
    description: heal players
  gui:
    description: a gui